allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  e1a89989-986d-4c34-b871-cb4cc81df548:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-14T15:46:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 420d0b54-9f18-41a9-b095-de7adfde688d # Ad - Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31eb0b50-e549-481b-a398-4bfb083f3fdc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-14T15:46:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bcb6d13b-de66-4331-8d15-bb23ef7a9736 # Ad - Link
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2b6a242-e008-409a-bcaf-306607cf0ec3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a24a74e-f8f0-420c-9d92-bb34a59f7a80
        userCondition: null
    thumbFieldKey: 'layoutElement:31eb0b50-e549-481b-a398-4bfb083f3fdc'
handle: ad
hasTitleField: false
icon: dollar-sign
name: Ad
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{adLink}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
