allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  2cc04b72-bbd9-4c62-bffc-5f982174c0f8:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:0c9c55be-9130-43f2-ae2e-ef2f0422289e'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-14T15:46:56+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 274b5d00-df3a-4b76-861b-ca591e2af249 # Contribution - User
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fc89327-b4dd-432c-bbcb-8cea0826756f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-14T15:46:56+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a46d69bc-dad9-44b6-9ca0-9ce75f501b7b # Contribution - Type
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c9c55be-9130-43f2-ae2e-ef2f0422289e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: babe03a7-c77f-44d6-b6f0-ced845b55aa9
        userCondition: null
    thumbFieldKey: null
handle: contribution
hasTitleField: false
icon: user
name: Contribution
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{contributionUser.one()}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
