allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  7da6fd3a-94c3-478f-a674-fab5f634e07d:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-14T15:46:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4d2d5d09-2278-47d1-8e63-1b70ad5116b4 # Content Gallery - Images
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15afb77a-b025-40a3-bff2-41c52bc5555b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7613751e-72da-4d7e-ab9e-7a2e5502883d
        userCondition: null
    thumbFieldKey: 'layoutElement:15afb77a-b025-40a3-bff2-41c52bc5555b'
handle: contentGallery
hasTitleField: false
icon: images
name: 'Content Gallery'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{contentGalleryImages.one()} (+{contentGalleryImages.count()})'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
