allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  6bf19c47-529b-409f-9459-24aa3459085c:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-14T15:46:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5e969c43-23fb-4bfc-a51a-e8e26b1b66ba # Content File - File
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d1f118b-fd00-4700-914e-21a4bef3051b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c7371210-a30f-49a5-a49a-22f4f0a5988f
        userCondition: null
    thumbFieldKey: 'layoutElement:3d1f118b-fd00-4700-914e-21a4bef3051b'
handle: contentFile
hasTitleField: false
icon: file
name: 'Content File'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{contentFileFile.one()}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
