allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  7d85c1a7-13d0-4bab-add9-cbbab124f4bd:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:8340a38c-1da8-493e-ad4e-358296d10491'
      - 'layoutElement:2a0f1edf-e710-4a28-9b00-3d655d23f0de'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-14T15:47:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 408c6114-fd69-445a-8240-e8841521181d # Subscription - Address
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 170859e7-a47e-499f-9dfd-a51dfdd46225
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-14T15:47:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b7794701-7ea0-40bb-8bba-27df38f94295 # Subscription - Email
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8340a38c-1da8-493e-ad4e-358296d10491
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-14T15:47:05+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 05e0aa7f-ad17-46bb-92fb-fde337d479b8
            userCondition: null
          -
            dateAdded: '2026-02-14T15:47:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 944c11ef-571f-4e08-a4bb-db2540e4b404 # Subscription - Plan
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a0f1edf-e710-4a28-9b00-3d655d23f0de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e2275e8b-2875-46a6-bada-461af233bab8
        userCondition: null
    thumbFieldKey: null
handle: subscription
hasTitleField: false
icon: mailbox
name: Subscription
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{subscriptionAddress.one().fullName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
