columnSuffix: null
handle: articleFormat
instructions: null
name: 'Article - Format'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:2ef3f3d8-ae1c-480e-a51b-db580170d832' # Formats
  targetSiteId: null
  validateRelatedElements: true
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
