columnSuffix: null
handle: contentNoteContent
instructions: null
name: 'Content Note - Content'
searchable: false
settings:
  advancedLinkFields: null
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: true
  headingLevels: false
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  options:
    __assoc__:
      -
        - list
        -
          __assoc__:
            -
              - multiBlock
              - false
            -
              - properties
              -
                __assoc__:
                  -
                    - styles
                    - false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - bulletedList
    - numberedList
    - '|'
    - bold
    - italic
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
