columnSuffix: irbejnhs
handle: homeSectionColor
instructions: null
name: 'Home Section - Color'
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
