columnSuffix: null
handle: timelineEvents
instructions: null
name: 'Timeline - Events'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 74e21a53-79cd-4aa7-85b3-bff442e02c68 # Timeline Event
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 683c8764-91e2-4a9e-b0cf-d7bed17d1d5d # Timeline Event (Article)
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
