defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2604525a-d068-477f-9621-13db45b69206 # Article
handle: articles
maxAuthors: 1
name: Articles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/article.twig
    uriFormat: "{postDate|date('Y')}/{postDate|date('m')}/{postDate|date('d')}/{slug}"
type: channel
